version: '3'
services:
  web:
    # Add because Windows sucks
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
        # Specify where the files for the image can be found
        context: .
        # Where dockerfile
        dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Tell docker to not map to node_modules folder inside container, since it does not exists
      - /app/node_modules
      - .:/app
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
    